name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check_yarn:
    runs-on: ubuntu-latest
    name: Check yarn
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Licence finder action
        uses: ./ # Uses an action in the root directory
        id: licence_finder_yarn
        with:
          folder: 'ci/actions/yarn'